-- Task 7: group aggregates as a materialized view.
--
-- Replaces code_test_preproc/02_data_preproc_for_speed.ipynb's
-- process_data_by_country, which computed a five-number summary (min, q1,
-- median, q3, max) plus a count, for every metric, for every country, field
-- and institution, for every edition, and pickled the result.
--
-- RULING R19: numbered 004, not 002 as the brief said, because migrations
-- apply in sorted filename order and this view groups by country_code, which
-- only exists once 003_row_country.sql has run.
--
-- RULING R17: grouped by career_metrics.country_code / singleyr_metrics.country_code
-- directly (added by 003), not by joining through institutions. 22,327 rows
-- have no institution at all and would vanish from a country aggregate built
-- by joining through institutions; another ~39,476 carry a country that
-- disagrees with their institution's.
--
-- RULING R22: this view originally covered all three groupings (country,
-- field, institution) here in 004, measuring 7,412,496 rows / 1,651 MB and
-- taking about 5m30s to build, only to have 005_group_metrics_narrow.sql
-- immediately drop it and rebuild it narrow (cntry and sm-field only,
-- 67,548 rows, about 15 MB). On a database that already had the wide view,
-- that two-step history is unavoidable and 005 stays as the migration that
-- narrows it. But a fresh database, such as `dokku run twopercenters
-- python db/migrate.py` produces on the server, has no existing view to
-- carry forward, so making 004 build the wide shape first was six minutes
-- and 1.65 GB of disk written and thrown away for nothing. 004 now creates
-- the narrow shape directly; 005 remains as an idempotent drop-and-recreate
-- so a database that already applied the old wide 004 still converges on
-- the same narrow view (see 005 for details).
--
-- Institution aggregates are not computed here at all; they are served live
-- instead by pipeline/institution_aggregate.py (see 005 and Task 9) for
-- group_kind 'inst_name'. The dashboard-facing shape (group_kind in
-- {cntry, sm-field, inst_name}, reachable for both 'career' and 'singleyr'
-- via editions.kind) is unchanged; only where the 'inst_name' rows come
-- from is different.
--
-- Metrics covered: process_data_by_country's metrics_list was
--   ['rank','c','nc','h','hm','ncs','ncsf','ncsfl','nps','cpsf','npsfl','npciting']
-- plus the same list with a ' (ns)' suffix, plus 'np' and 'self%' -- 26 in
-- total. Every one of those has a same-named (non-suffixed) or _ns-suffixed
-- or self_pct column on career_metrics / singleyr_metrics (001_schema.sql).
-- Metric names here match the column names (e.g. 'nc_ns', 'self_pct'); the
-- notebook's cosmetic '(ns)'/'self%' spellings are a display concern for
-- whatever reads this view, not stored here.
--
-- Null handling: process_data_by_country dropped rows with a null grouping
-- key (dropna(subset=[aggmetric])) but did NOT drop rows with a null value
-- for an individual metric before computing percentiles over that metric's
-- column -- a stray NaN would have silently poisoned that one metric's
-- summary. This view instead excludes, per metric, only the rows where that
-- particular metric is null, so a null in one column never contaminates
-- another metric's summary and `n` is an honest non-null count for that
-- metric. This is a deliberate improvement, not a faithful reproduction of
-- that incidental behaviour.
--
-- Quartiles use percentile_cont, matching the notebook's
-- np.percentile(stuff, [25, 50, 75]) (linear interpolation).
create materialized view group_metrics as
with career_wide_cntry as (
    select
        cm.edition_id,
        cm.country_code as group_value,
        min(cm.rank) as rank_min,
        percentile_cont(0.25) within group (order by cm.rank::double precision) as rank_q1,
        percentile_cont(0.5) within group (order by cm.rank::double precision) as rank_median,
        percentile_cont(0.75) within group (order by cm.rank::double precision) as rank_q3,
        max(cm.rank) as rank_max,
        count(cm.rank) as rank_n,
        min(cm.c) as c_min,
        percentile_cont(0.25) within group (order by cm.c::double precision) as c_q1,
        percentile_cont(0.5) within group (order by cm.c::double precision) as c_median,
        percentile_cont(0.75) within group (order by cm.c::double precision) as c_q3,
        max(cm.c) as c_max,
        count(cm.c) as c_n,
        min(cm.nc) as nc_min,
        percentile_cont(0.25) within group (order by cm.nc::double precision) as nc_q1,
        percentile_cont(0.5) within group (order by cm.nc::double precision) as nc_median,
        percentile_cont(0.75) within group (order by cm.nc::double precision) as nc_q3,
        max(cm.nc) as nc_max,
        count(cm.nc) as nc_n,
        min(cm.h) as h_min,
        percentile_cont(0.25) within group (order by cm.h::double precision) as h_q1,
        percentile_cont(0.5) within group (order by cm.h::double precision) as h_median,
        percentile_cont(0.75) within group (order by cm.h::double precision) as h_q3,
        max(cm.h) as h_max,
        count(cm.h) as h_n,
        min(cm.hm) as hm_min,
        percentile_cont(0.25) within group (order by cm.hm::double precision) as hm_q1,
        percentile_cont(0.5) within group (order by cm.hm::double precision) as hm_median,
        percentile_cont(0.75) within group (order by cm.hm::double precision) as hm_q3,
        max(cm.hm) as hm_max,
        count(cm.hm) as hm_n,
        min(cm.ncs) as ncs_min,
        percentile_cont(0.25) within group (order by cm.ncs::double precision) as ncs_q1,
        percentile_cont(0.5) within group (order by cm.ncs::double precision) as ncs_median,
        percentile_cont(0.75) within group (order by cm.ncs::double precision) as ncs_q3,
        max(cm.ncs) as ncs_max,
        count(cm.ncs) as ncs_n,
        min(cm.ncsf) as ncsf_min,
        percentile_cont(0.25) within group (order by cm.ncsf::double precision) as ncsf_q1,
        percentile_cont(0.5) within group (order by cm.ncsf::double precision) as ncsf_median,
        percentile_cont(0.75) within group (order by cm.ncsf::double precision) as ncsf_q3,
        max(cm.ncsf) as ncsf_max,
        count(cm.ncsf) as ncsf_n,
        min(cm.ncsfl) as ncsfl_min,
        percentile_cont(0.25) within group (order by cm.ncsfl::double precision) as ncsfl_q1,
        percentile_cont(0.5) within group (order by cm.ncsfl::double precision) as ncsfl_median,
        percentile_cont(0.75) within group (order by cm.ncsfl::double precision) as ncsfl_q3,
        max(cm.ncsfl) as ncsfl_max,
        count(cm.ncsfl) as ncsfl_n,
        min(cm.nps) as nps_min,
        percentile_cont(0.25) within group (order by cm.nps::double precision) as nps_q1,
        percentile_cont(0.5) within group (order by cm.nps::double precision) as nps_median,
        percentile_cont(0.75) within group (order by cm.nps::double precision) as nps_q3,
        max(cm.nps) as nps_max,
        count(cm.nps) as nps_n,
        min(cm.cpsf) as cpsf_min,
        percentile_cont(0.25) within group (order by cm.cpsf::double precision) as cpsf_q1,
        percentile_cont(0.5) within group (order by cm.cpsf::double precision) as cpsf_median,
        percentile_cont(0.75) within group (order by cm.cpsf::double precision) as cpsf_q3,
        max(cm.cpsf) as cpsf_max,
        count(cm.cpsf) as cpsf_n,
        min(cm.npsfl) as npsfl_min,
        percentile_cont(0.25) within group (order by cm.npsfl::double precision) as npsfl_q1,
        percentile_cont(0.5) within group (order by cm.npsfl::double precision) as npsfl_median,
        percentile_cont(0.75) within group (order by cm.npsfl::double precision) as npsfl_q3,
        max(cm.npsfl) as npsfl_max,
        count(cm.npsfl) as npsfl_n,
        min(cm.npciting) as npciting_min,
        percentile_cont(0.25) within group (order by cm.npciting::double precision) as npciting_q1,
        percentile_cont(0.5) within group (order by cm.npciting::double precision) as npciting_median,
        percentile_cont(0.75) within group (order by cm.npciting::double precision) as npciting_q3,
        max(cm.npciting) as npciting_max,
        count(cm.npciting) as npciting_n,
        min(cm.rank_ns) as rank_ns_min,
        percentile_cont(0.25) within group (order by cm.rank_ns::double precision) as rank_ns_q1,
        percentile_cont(0.5) within group (order by cm.rank_ns::double precision) as rank_ns_median,
        percentile_cont(0.75) within group (order by cm.rank_ns::double precision) as rank_ns_q3,
        max(cm.rank_ns) as rank_ns_max,
        count(cm.rank_ns) as rank_ns_n,
        min(cm.c_ns) as c_ns_min,
        percentile_cont(0.25) within group (order by cm.c_ns::double precision) as c_ns_q1,
        percentile_cont(0.5) within group (order by cm.c_ns::double precision) as c_ns_median,
        percentile_cont(0.75) within group (order by cm.c_ns::double precision) as c_ns_q3,
        max(cm.c_ns) as c_ns_max,
        count(cm.c_ns) as c_ns_n,
        min(cm.nc_ns) as nc_ns_min,
        percentile_cont(0.25) within group (order by cm.nc_ns::double precision) as nc_ns_q1,
        percentile_cont(0.5) within group (order by cm.nc_ns::double precision) as nc_ns_median,
        percentile_cont(0.75) within group (order by cm.nc_ns::double precision) as nc_ns_q3,
        max(cm.nc_ns) as nc_ns_max,
        count(cm.nc_ns) as nc_ns_n,
        min(cm.h_ns) as h_ns_min,
        percentile_cont(0.25) within group (order by cm.h_ns::double precision) as h_ns_q1,
        percentile_cont(0.5) within group (order by cm.h_ns::double precision) as h_ns_median,
        percentile_cont(0.75) within group (order by cm.h_ns::double precision) as h_ns_q3,
        max(cm.h_ns) as h_ns_max,
        count(cm.h_ns) as h_ns_n,
        min(cm.hm_ns) as hm_ns_min,
        percentile_cont(0.25) within group (order by cm.hm_ns::double precision) as hm_ns_q1,
        percentile_cont(0.5) within group (order by cm.hm_ns::double precision) as hm_ns_median,
        percentile_cont(0.75) within group (order by cm.hm_ns::double precision) as hm_ns_q3,
        max(cm.hm_ns) as hm_ns_max,
        count(cm.hm_ns) as hm_ns_n,
        min(cm.ncs_ns) as ncs_ns_min,
        percentile_cont(0.25) within group (order by cm.ncs_ns::double precision) as ncs_ns_q1,
        percentile_cont(0.5) within group (order by cm.ncs_ns::double precision) as ncs_ns_median,
        percentile_cont(0.75) within group (order by cm.ncs_ns::double precision) as ncs_ns_q3,
        max(cm.ncs_ns) as ncs_ns_max,
        count(cm.ncs_ns) as ncs_ns_n,
        min(cm.ncsf_ns) as ncsf_ns_min,
        percentile_cont(0.25) within group (order by cm.ncsf_ns::double precision) as ncsf_ns_q1,
        percentile_cont(0.5) within group (order by cm.ncsf_ns::double precision) as ncsf_ns_median,
        percentile_cont(0.75) within group (order by cm.ncsf_ns::double precision) as ncsf_ns_q3,
        max(cm.ncsf_ns) as ncsf_ns_max,
        count(cm.ncsf_ns) as ncsf_ns_n,
        min(cm.ncsfl_ns) as ncsfl_ns_min,
        percentile_cont(0.25) within group (order by cm.ncsfl_ns::double precision) as ncsfl_ns_q1,
        percentile_cont(0.5) within group (order by cm.ncsfl_ns::double precision) as ncsfl_ns_median,
        percentile_cont(0.75) within group (order by cm.ncsfl_ns::double precision) as ncsfl_ns_q3,
        max(cm.ncsfl_ns) as ncsfl_ns_max,
        count(cm.ncsfl_ns) as ncsfl_ns_n,
        min(cm.nps_ns) as nps_ns_min,
        percentile_cont(0.25) within group (order by cm.nps_ns::double precision) as nps_ns_q1,
        percentile_cont(0.5) within group (order by cm.nps_ns::double precision) as nps_ns_median,
        percentile_cont(0.75) within group (order by cm.nps_ns::double precision) as nps_ns_q3,
        max(cm.nps_ns) as nps_ns_max,
        count(cm.nps_ns) as nps_ns_n,
        min(cm.cpsf_ns) as cpsf_ns_min,
        percentile_cont(0.25) within group (order by cm.cpsf_ns::double precision) as cpsf_ns_q1,
        percentile_cont(0.5) within group (order by cm.cpsf_ns::double precision) as cpsf_ns_median,
        percentile_cont(0.75) within group (order by cm.cpsf_ns::double precision) as cpsf_ns_q3,
        max(cm.cpsf_ns) as cpsf_ns_max,
        count(cm.cpsf_ns) as cpsf_ns_n,
        min(cm.npsfl_ns) as npsfl_ns_min,
        percentile_cont(0.25) within group (order by cm.npsfl_ns::double precision) as npsfl_ns_q1,
        percentile_cont(0.5) within group (order by cm.npsfl_ns::double precision) as npsfl_ns_median,
        percentile_cont(0.75) within group (order by cm.npsfl_ns::double precision) as npsfl_ns_q3,
        max(cm.npsfl_ns) as npsfl_ns_max,
        count(cm.npsfl_ns) as npsfl_ns_n,
        min(cm.npciting_ns) as npciting_ns_min,
        percentile_cont(0.25) within group (order by cm.npciting_ns::double precision) as npciting_ns_q1,
        percentile_cont(0.5) within group (order by cm.npciting_ns::double precision) as npciting_ns_median,
        percentile_cont(0.75) within group (order by cm.npciting_ns::double precision) as npciting_ns_q3,
        max(cm.npciting_ns) as npciting_ns_max,
        count(cm.npciting_ns) as npciting_ns_n,
        min(cm.np) as np_min,
        percentile_cont(0.25) within group (order by cm.np::double precision) as np_q1,
        percentile_cont(0.5) within group (order by cm.np::double precision) as np_median,
        percentile_cont(0.75) within group (order by cm.np::double precision) as np_q3,
        max(cm.np) as np_max,
        count(cm.np) as np_n,
        min(cm.self_pct) as self_pct_min,
        percentile_cont(0.25) within group (order by cm.self_pct::double precision) as self_pct_q1,
        percentile_cont(0.5) within group (order by cm.self_pct::double precision) as self_pct_median,
        percentile_cont(0.75) within group (order by cm.self_pct::double precision) as self_pct_q3,
        max(cm.self_pct) as self_pct_max,
        count(cm.self_pct) as self_pct_n
    from career_metrics cm
    where cm.country_code is not null
    group by cm.edition_id, cm.country_code
),
career_wide_field as (
    select
        cm.edition_id,
        f.name as group_value,
        min(cm.rank) as rank_min,
        percentile_cont(0.25) within group (order by cm.rank::double precision) as rank_q1,
        percentile_cont(0.5) within group (order by cm.rank::double precision) as rank_median,
        percentile_cont(0.75) within group (order by cm.rank::double precision) as rank_q3,
        max(cm.rank) as rank_max,
        count(cm.rank) as rank_n,
        min(cm.c) as c_min,
        percentile_cont(0.25) within group (order by cm.c::double precision) as c_q1,
        percentile_cont(0.5) within group (order by cm.c::double precision) as c_median,
        percentile_cont(0.75) within group (order by cm.c::double precision) as c_q3,
        max(cm.c) as c_max,
        count(cm.c) as c_n,
        min(cm.nc) as nc_min,
        percentile_cont(0.25) within group (order by cm.nc::double precision) as nc_q1,
        percentile_cont(0.5) within group (order by cm.nc::double precision) as nc_median,
        percentile_cont(0.75) within group (order by cm.nc::double precision) as nc_q3,
        max(cm.nc) as nc_max,
        count(cm.nc) as nc_n,
        min(cm.h) as h_min,
        percentile_cont(0.25) within group (order by cm.h::double precision) as h_q1,
        percentile_cont(0.5) within group (order by cm.h::double precision) as h_median,
        percentile_cont(0.75) within group (order by cm.h::double precision) as h_q3,
        max(cm.h) as h_max,
        count(cm.h) as h_n,
        min(cm.hm) as hm_min,
        percentile_cont(0.25) within group (order by cm.hm::double precision) as hm_q1,
        percentile_cont(0.5) within group (order by cm.hm::double precision) as hm_median,
        percentile_cont(0.75) within group (order by cm.hm::double precision) as hm_q3,
        max(cm.hm) as hm_max,
        count(cm.hm) as hm_n,
        min(cm.ncs) as ncs_min,
        percentile_cont(0.25) within group (order by cm.ncs::double precision) as ncs_q1,
        percentile_cont(0.5) within group (order by cm.ncs::double precision) as ncs_median,
        percentile_cont(0.75) within group (order by cm.ncs::double precision) as ncs_q3,
        max(cm.ncs) as ncs_max,
        count(cm.ncs) as ncs_n,
        min(cm.ncsf) as ncsf_min,
        percentile_cont(0.25) within group (order by cm.ncsf::double precision) as ncsf_q1,
        percentile_cont(0.5) within group (order by cm.ncsf::double precision) as ncsf_median,
        percentile_cont(0.75) within group (order by cm.ncsf::double precision) as ncsf_q3,
        max(cm.ncsf) as ncsf_max,
        count(cm.ncsf) as ncsf_n,
        min(cm.ncsfl) as ncsfl_min,
        percentile_cont(0.25) within group (order by cm.ncsfl::double precision) as ncsfl_q1,
        percentile_cont(0.5) within group (order by cm.ncsfl::double precision) as ncsfl_median,
        percentile_cont(0.75) within group (order by cm.ncsfl::double precision) as ncsfl_q3,
        max(cm.ncsfl) as ncsfl_max,
        count(cm.ncsfl) as ncsfl_n,
        min(cm.nps) as nps_min,
        percentile_cont(0.25) within group (order by cm.nps::double precision) as nps_q1,
        percentile_cont(0.5) within group (order by cm.nps::double precision) as nps_median,
        percentile_cont(0.75) within group (order by cm.nps::double precision) as nps_q3,
        max(cm.nps) as nps_max,
        count(cm.nps) as nps_n,
        min(cm.cpsf) as cpsf_min,
        percentile_cont(0.25) within group (order by cm.cpsf::double precision) as cpsf_q1,
        percentile_cont(0.5) within group (order by cm.cpsf::double precision) as cpsf_median,
        percentile_cont(0.75) within group (order by cm.cpsf::double precision) as cpsf_q3,
        max(cm.cpsf) as cpsf_max,
        count(cm.cpsf) as cpsf_n,
        min(cm.npsfl) as npsfl_min,
        percentile_cont(0.25) within group (order by cm.npsfl::double precision) as npsfl_q1,
        percentile_cont(0.5) within group (order by cm.npsfl::double precision) as npsfl_median,
        percentile_cont(0.75) within group (order by cm.npsfl::double precision) as npsfl_q3,
        max(cm.npsfl) as npsfl_max,
        count(cm.npsfl) as npsfl_n,
        min(cm.npciting) as npciting_min,
        percentile_cont(0.25) within group (order by cm.npciting::double precision) as npciting_q1,
        percentile_cont(0.5) within group (order by cm.npciting::double precision) as npciting_median,
        percentile_cont(0.75) within group (order by cm.npciting::double precision) as npciting_q3,
        max(cm.npciting) as npciting_max,
        count(cm.npciting) as npciting_n,
        min(cm.rank_ns) as rank_ns_min,
        percentile_cont(0.25) within group (order by cm.rank_ns::double precision) as rank_ns_q1,
        percentile_cont(0.5) within group (order by cm.rank_ns::double precision) as rank_ns_median,
        percentile_cont(0.75) within group (order by cm.rank_ns::double precision) as rank_ns_q3,
        max(cm.rank_ns) as rank_ns_max,
        count(cm.rank_ns) as rank_ns_n,
        min(cm.c_ns) as c_ns_min,
        percentile_cont(0.25) within group (order by cm.c_ns::double precision) as c_ns_q1,
        percentile_cont(0.5) within group (order by cm.c_ns::double precision) as c_ns_median,
        percentile_cont(0.75) within group (order by cm.c_ns::double precision) as c_ns_q3,
        max(cm.c_ns) as c_ns_max,
        count(cm.c_ns) as c_ns_n,
        min(cm.nc_ns) as nc_ns_min,
        percentile_cont(0.25) within group (order by cm.nc_ns::double precision) as nc_ns_q1,
        percentile_cont(0.5) within group (order by cm.nc_ns::double precision) as nc_ns_median,
        percentile_cont(0.75) within group (order by cm.nc_ns::double precision) as nc_ns_q3,
        max(cm.nc_ns) as nc_ns_max,
        count(cm.nc_ns) as nc_ns_n,
        min(cm.h_ns) as h_ns_min,
        percentile_cont(0.25) within group (order by cm.h_ns::double precision) as h_ns_q1,
        percentile_cont(0.5) within group (order by cm.h_ns::double precision) as h_ns_median,
        percentile_cont(0.75) within group (order by cm.h_ns::double precision) as h_ns_q3,
        max(cm.h_ns) as h_ns_max,
        count(cm.h_ns) as h_ns_n,
        min(cm.hm_ns) as hm_ns_min,
        percentile_cont(0.25) within group (order by cm.hm_ns::double precision) as hm_ns_q1,
        percentile_cont(0.5) within group (order by cm.hm_ns::double precision) as hm_ns_median,
        percentile_cont(0.75) within group (order by cm.hm_ns::double precision) as hm_ns_q3,
        max(cm.hm_ns) as hm_ns_max,
        count(cm.hm_ns) as hm_ns_n,
        min(cm.ncs_ns) as ncs_ns_min,
        percentile_cont(0.25) within group (order by cm.ncs_ns::double precision) as ncs_ns_q1,
        percentile_cont(0.5) within group (order by cm.ncs_ns::double precision) as ncs_ns_median,
        percentile_cont(0.75) within group (order by cm.ncs_ns::double precision) as ncs_ns_q3,
        max(cm.ncs_ns) as ncs_ns_max,
        count(cm.ncs_ns) as ncs_ns_n,
        min(cm.ncsf_ns) as ncsf_ns_min,
        percentile_cont(0.25) within group (order by cm.ncsf_ns::double precision) as ncsf_ns_q1,
        percentile_cont(0.5) within group (order by cm.ncsf_ns::double precision) as ncsf_ns_median,
        percentile_cont(0.75) within group (order by cm.ncsf_ns::double precision) as ncsf_ns_q3,
        max(cm.ncsf_ns) as ncsf_ns_max,
        count(cm.ncsf_ns) as ncsf_ns_n,
        min(cm.ncsfl_ns) as ncsfl_ns_min,
        percentile_cont(0.25) within group (order by cm.ncsfl_ns::double precision) as ncsfl_ns_q1,
        percentile_cont(0.5) within group (order by cm.ncsfl_ns::double precision) as ncsfl_ns_median,
        percentile_cont(0.75) within group (order by cm.ncsfl_ns::double precision) as ncsfl_ns_q3,
        max(cm.ncsfl_ns) as ncsfl_ns_max,
        count(cm.ncsfl_ns) as ncsfl_ns_n,
        min(cm.nps_ns) as nps_ns_min,
        percentile_cont(0.25) within group (order by cm.nps_ns::double precision) as nps_ns_q1,
        percentile_cont(0.5) within group (order by cm.nps_ns::double precision) as nps_ns_median,
        percentile_cont(0.75) within group (order by cm.nps_ns::double precision) as nps_ns_q3,
        max(cm.nps_ns) as nps_ns_max,
        count(cm.nps_ns) as nps_ns_n,
        min(cm.cpsf_ns) as cpsf_ns_min,
        percentile_cont(0.25) within group (order by cm.cpsf_ns::double precision) as cpsf_ns_q1,
        percentile_cont(0.5) within group (order by cm.cpsf_ns::double precision) as cpsf_ns_median,
        percentile_cont(0.75) within group (order by cm.cpsf_ns::double precision) as cpsf_ns_q3,
        max(cm.cpsf_ns) as cpsf_ns_max,
        count(cm.cpsf_ns) as cpsf_ns_n,
        min(cm.npsfl_ns) as npsfl_ns_min,
        percentile_cont(0.25) within group (order by cm.npsfl_ns::double precision) as npsfl_ns_q1,
        percentile_cont(0.5) within group (order by cm.npsfl_ns::double precision) as npsfl_ns_median,
        percentile_cont(0.75) within group (order by cm.npsfl_ns::double precision) as npsfl_ns_q3,
        max(cm.npsfl_ns) as npsfl_ns_max,
        count(cm.npsfl_ns) as npsfl_ns_n,
        min(cm.npciting_ns) as npciting_ns_min,
        percentile_cont(0.25) within group (order by cm.npciting_ns::double precision) as npciting_ns_q1,
        percentile_cont(0.5) within group (order by cm.npciting_ns::double precision) as npciting_ns_median,
        percentile_cont(0.75) within group (order by cm.npciting_ns::double precision) as npciting_ns_q3,
        max(cm.npciting_ns) as npciting_ns_max,
        count(cm.npciting_ns) as npciting_ns_n,
        min(cm.np) as np_min,
        percentile_cont(0.25) within group (order by cm.np::double precision) as np_q1,
        percentile_cont(0.5) within group (order by cm.np::double precision) as np_median,
        percentile_cont(0.75) within group (order by cm.np::double precision) as np_q3,
        max(cm.np) as np_max,
        count(cm.np) as np_n,
        min(cm.self_pct) as self_pct_min,
        percentile_cont(0.25) within group (order by cm.self_pct::double precision) as self_pct_q1,
        percentile_cont(0.5) within group (order by cm.self_pct::double precision) as self_pct_median,
        percentile_cont(0.75) within group (order by cm.self_pct::double precision) as self_pct_q3,
        max(cm.self_pct) as self_pct_max,
        count(cm.self_pct) as self_pct_n
    from career_metrics cm
    join fields f on f.field_id = cm.field_id
    where cm.field_id is not null
    group by cm.edition_id, f.name
),
singleyr_wide_cntry as (
    select
        sm.edition_id,
        sm.country_code as group_value,
        min(sm.rank) as rank_min,
        percentile_cont(0.25) within group (order by sm.rank::double precision) as rank_q1,
        percentile_cont(0.5) within group (order by sm.rank::double precision) as rank_median,
        percentile_cont(0.75) within group (order by sm.rank::double precision) as rank_q3,
        max(sm.rank) as rank_max,
        count(sm.rank) as rank_n,
        min(sm.c) as c_min,
        percentile_cont(0.25) within group (order by sm.c::double precision) as c_q1,
        percentile_cont(0.5) within group (order by sm.c::double precision) as c_median,
        percentile_cont(0.75) within group (order by sm.c::double precision) as c_q3,
        max(sm.c) as c_max,
        count(sm.c) as c_n,
        min(sm.nc) as nc_min,
        percentile_cont(0.25) within group (order by sm.nc::double precision) as nc_q1,
        percentile_cont(0.5) within group (order by sm.nc::double precision) as nc_median,
        percentile_cont(0.75) within group (order by sm.nc::double precision) as nc_q3,
        max(sm.nc) as nc_max,
        count(sm.nc) as nc_n,
        min(sm.h) as h_min,
        percentile_cont(0.25) within group (order by sm.h::double precision) as h_q1,
        percentile_cont(0.5) within group (order by sm.h::double precision) as h_median,
        percentile_cont(0.75) within group (order by sm.h::double precision) as h_q3,
        max(sm.h) as h_max,
        count(sm.h) as h_n,
        min(sm.hm) as hm_min,
        percentile_cont(0.25) within group (order by sm.hm::double precision) as hm_q1,
        percentile_cont(0.5) within group (order by sm.hm::double precision) as hm_median,
        percentile_cont(0.75) within group (order by sm.hm::double precision) as hm_q3,
        max(sm.hm) as hm_max,
        count(sm.hm) as hm_n,
        min(sm.ncs) as ncs_min,
        percentile_cont(0.25) within group (order by sm.ncs::double precision) as ncs_q1,
        percentile_cont(0.5) within group (order by sm.ncs::double precision) as ncs_median,
        percentile_cont(0.75) within group (order by sm.ncs::double precision) as ncs_q3,
        max(sm.ncs) as ncs_max,
        count(sm.ncs) as ncs_n,
        min(sm.ncsf) as ncsf_min,
        percentile_cont(0.25) within group (order by sm.ncsf::double precision) as ncsf_q1,
        percentile_cont(0.5) within group (order by sm.ncsf::double precision) as ncsf_median,
        percentile_cont(0.75) within group (order by sm.ncsf::double precision) as ncsf_q3,
        max(sm.ncsf) as ncsf_max,
        count(sm.ncsf) as ncsf_n,
        min(sm.ncsfl) as ncsfl_min,
        percentile_cont(0.25) within group (order by sm.ncsfl::double precision) as ncsfl_q1,
        percentile_cont(0.5) within group (order by sm.ncsfl::double precision) as ncsfl_median,
        percentile_cont(0.75) within group (order by sm.ncsfl::double precision) as ncsfl_q3,
        max(sm.ncsfl) as ncsfl_max,
        count(sm.ncsfl) as ncsfl_n,
        min(sm.nps) as nps_min,
        percentile_cont(0.25) within group (order by sm.nps::double precision) as nps_q1,
        percentile_cont(0.5) within group (order by sm.nps::double precision) as nps_median,
        percentile_cont(0.75) within group (order by sm.nps::double precision) as nps_q3,
        max(sm.nps) as nps_max,
        count(sm.nps) as nps_n,
        min(sm.cpsf) as cpsf_min,
        percentile_cont(0.25) within group (order by sm.cpsf::double precision) as cpsf_q1,
        percentile_cont(0.5) within group (order by sm.cpsf::double precision) as cpsf_median,
        percentile_cont(0.75) within group (order by sm.cpsf::double precision) as cpsf_q3,
        max(sm.cpsf) as cpsf_max,
        count(sm.cpsf) as cpsf_n,
        min(sm.npsfl) as npsfl_min,
        percentile_cont(0.25) within group (order by sm.npsfl::double precision) as npsfl_q1,
        percentile_cont(0.5) within group (order by sm.npsfl::double precision) as npsfl_median,
        percentile_cont(0.75) within group (order by sm.npsfl::double precision) as npsfl_q3,
        max(sm.npsfl) as npsfl_max,
        count(sm.npsfl) as npsfl_n,
        min(sm.npciting) as npciting_min,
        percentile_cont(0.25) within group (order by sm.npciting::double precision) as npciting_q1,
        percentile_cont(0.5) within group (order by sm.npciting::double precision) as npciting_median,
        percentile_cont(0.75) within group (order by sm.npciting::double precision) as npciting_q3,
        max(sm.npciting) as npciting_max,
        count(sm.npciting) as npciting_n,
        min(sm.rank_ns) as rank_ns_min,
        percentile_cont(0.25) within group (order by sm.rank_ns::double precision) as rank_ns_q1,
        percentile_cont(0.5) within group (order by sm.rank_ns::double precision) as rank_ns_median,
        percentile_cont(0.75) within group (order by sm.rank_ns::double precision) as rank_ns_q3,
        max(sm.rank_ns) as rank_ns_max,
        count(sm.rank_ns) as rank_ns_n,
        min(sm.c_ns) as c_ns_min,
        percentile_cont(0.25) within group (order by sm.c_ns::double precision) as c_ns_q1,
        percentile_cont(0.5) within group (order by sm.c_ns::double precision) as c_ns_median,
        percentile_cont(0.75) within group (order by sm.c_ns::double precision) as c_ns_q3,
        max(sm.c_ns) as c_ns_max,
        count(sm.c_ns) as c_ns_n,
        min(sm.nc_ns) as nc_ns_min,
        percentile_cont(0.25) within group (order by sm.nc_ns::double precision) as nc_ns_q1,
        percentile_cont(0.5) within group (order by sm.nc_ns::double precision) as nc_ns_median,
        percentile_cont(0.75) within group (order by sm.nc_ns::double precision) as nc_ns_q3,
        max(sm.nc_ns) as nc_ns_max,
        count(sm.nc_ns) as nc_ns_n,
        min(sm.h_ns) as h_ns_min,
        percentile_cont(0.25) within group (order by sm.h_ns::double precision) as h_ns_q1,
        percentile_cont(0.5) within group (order by sm.h_ns::double precision) as h_ns_median,
        percentile_cont(0.75) within group (order by sm.h_ns::double precision) as h_ns_q3,
        max(sm.h_ns) as h_ns_max,
        count(sm.h_ns) as h_ns_n,
        min(sm.hm_ns) as hm_ns_min,
        percentile_cont(0.25) within group (order by sm.hm_ns::double precision) as hm_ns_q1,
        percentile_cont(0.5) within group (order by sm.hm_ns::double precision) as hm_ns_median,
        percentile_cont(0.75) within group (order by sm.hm_ns::double precision) as hm_ns_q3,
        max(sm.hm_ns) as hm_ns_max,
        count(sm.hm_ns) as hm_ns_n,
        min(sm.ncs_ns) as ncs_ns_min,
        percentile_cont(0.25) within group (order by sm.ncs_ns::double precision) as ncs_ns_q1,
        percentile_cont(0.5) within group (order by sm.ncs_ns::double precision) as ncs_ns_median,
        percentile_cont(0.75) within group (order by sm.ncs_ns::double precision) as ncs_ns_q3,
        max(sm.ncs_ns) as ncs_ns_max,
        count(sm.ncs_ns) as ncs_ns_n,
        min(sm.ncsf_ns) as ncsf_ns_min,
        percentile_cont(0.25) within group (order by sm.ncsf_ns::double precision) as ncsf_ns_q1,
        percentile_cont(0.5) within group (order by sm.ncsf_ns::double precision) as ncsf_ns_median,
        percentile_cont(0.75) within group (order by sm.ncsf_ns::double precision) as ncsf_ns_q3,
        max(sm.ncsf_ns) as ncsf_ns_max,
        count(sm.ncsf_ns) as ncsf_ns_n,
        min(sm.ncsfl_ns) as ncsfl_ns_min,
        percentile_cont(0.25) within group (order by sm.ncsfl_ns::double precision) as ncsfl_ns_q1,
        percentile_cont(0.5) within group (order by sm.ncsfl_ns::double precision) as ncsfl_ns_median,
        percentile_cont(0.75) within group (order by sm.ncsfl_ns::double precision) as ncsfl_ns_q3,
        max(sm.ncsfl_ns) as ncsfl_ns_max,
        count(sm.ncsfl_ns) as ncsfl_ns_n,
        min(sm.nps_ns) as nps_ns_min,
        percentile_cont(0.25) within group (order by sm.nps_ns::double precision) as nps_ns_q1,
        percentile_cont(0.5) within group (order by sm.nps_ns::double precision) as nps_ns_median,
        percentile_cont(0.75) within group (order by sm.nps_ns::double precision) as nps_ns_q3,
        max(sm.nps_ns) as nps_ns_max,
        count(sm.nps_ns) as nps_ns_n,
        min(sm.cpsf_ns) as cpsf_ns_min,
        percentile_cont(0.25) within group (order by sm.cpsf_ns::double precision) as cpsf_ns_q1,
        percentile_cont(0.5) within group (order by sm.cpsf_ns::double precision) as cpsf_ns_median,
        percentile_cont(0.75) within group (order by sm.cpsf_ns::double precision) as cpsf_ns_q3,
        max(sm.cpsf_ns) as cpsf_ns_max,
        count(sm.cpsf_ns) as cpsf_ns_n,
        min(sm.npsfl_ns) as npsfl_ns_min,
        percentile_cont(0.25) within group (order by sm.npsfl_ns::double precision) as npsfl_ns_q1,
        percentile_cont(0.5) within group (order by sm.npsfl_ns::double precision) as npsfl_ns_median,
        percentile_cont(0.75) within group (order by sm.npsfl_ns::double precision) as npsfl_ns_q3,
        max(sm.npsfl_ns) as npsfl_ns_max,
        count(sm.npsfl_ns) as npsfl_ns_n,
        min(sm.npciting_ns) as npciting_ns_min,
        percentile_cont(0.25) within group (order by sm.npciting_ns::double precision) as npciting_ns_q1,
        percentile_cont(0.5) within group (order by sm.npciting_ns::double precision) as npciting_ns_median,
        percentile_cont(0.75) within group (order by sm.npciting_ns::double precision) as npciting_ns_q3,
        max(sm.npciting_ns) as npciting_ns_max,
        count(sm.npciting_ns) as npciting_ns_n,
        min(sm.np) as np_min,
        percentile_cont(0.25) within group (order by sm.np::double precision) as np_q1,
        percentile_cont(0.5) within group (order by sm.np::double precision) as np_median,
        percentile_cont(0.75) within group (order by sm.np::double precision) as np_q3,
        max(sm.np) as np_max,
        count(sm.np) as np_n,
        min(sm.self_pct) as self_pct_min,
        percentile_cont(0.25) within group (order by sm.self_pct::double precision) as self_pct_q1,
        percentile_cont(0.5) within group (order by sm.self_pct::double precision) as self_pct_median,
        percentile_cont(0.75) within group (order by sm.self_pct::double precision) as self_pct_q3,
        max(sm.self_pct) as self_pct_max,
        count(sm.self_pct) as self_pct_n
    from singleyr_metrics sm
    where sm.country_code is not null
    group by sm.edition_id, sm.country_code
),
singleyr_wide_field as (
    select
        sm.edition_id,
        f.name as group_value,
        min(sm.rank) as rank_min,
        percentile_cont(0.25) within group (order by sm.rank::double precision) as rank_q1,
        percentile_cont(0.5) within group (order by sm.rank::double precision) as rank_median,
        percentile_cont(0.75) within group (order by sm.rank::double precision) as rank_q3,
        max(sm.rank) as rank_max,
        count(sm.rank) as rank_n,
        min(sm.c) as c_min,
        percentile_cont(0.25) within group (order by sm.c::double precision) as c_q1,
        percentile_cont(0.5) within group (order by sm.c::double precision) as c_median,
        percentile_cont(0.75) within group (order by sm.c::double precision) as c_q3,
        max(sm.c) as c_max,
        count(sm.c) as c_n,
        min(sm.nc) as nc_min,
        percentile_cont(0.25) within group (order by sm.nc::double precision) as nc_q1,
        percentile_cont(0.5) within group (order by sm.nc::double precision) as nc_median,
        percentile_cont(0.75) within group (order by sm.nc::double precision) as nc_q3,
        max(sm.nc) as nc_max,
        count(sm.nc) as nc_n,
        min(sm.h) as h_min,
        percentile_cont(0.25) within group (order by sm.h::double precision) as h_q1,
        percentile_cont(0.5) within group (order by sm.h::double precision) as h_median,
        percentile_cont(0.75) within group (order by sm.h::double precision) as h_q3,
        max(sm.h) as h_max,
        count(sm.h) as h_n,
        min(sm.hm) as hm_min,
        percentile_cont(0.25) within group (order by sm.hm::double precision) as hm_q1,
        percentile_cont(0.5) within group (order by sm.hm::double precision) as hm_median,
        percentile_cont(0.75) within group (order by sm.hm::double precision) as hm_q3,
        max(sm.hm) as hm_max,
        count(sm.hm) as hm_n,
        min(sm.ncs) as ncs_min,
        percentile_cont(0.25) within group (order by sm.ncs::double precision) as ncs_q1,
        percentile_cont(0.5) within group (order by sm.ncs::double precision) as ncs_median,
        percentile_cont(0.75) within group (order by sm.ncs::double precision) as ncs_q3,
        max(sm.ncs) as ncs_max,
        count(sm.ncs) as ncs_n,
        min(sm.ncsf) as ncsf_min,
        percentile_cont(0.25) within group (order by sm.ncsf::double precision) as ncsf_q1,
        percentile_cont(0.5) within group (order by sm.ncsf::double precision) as ncsf_median,
        percentile_cont(0.75) within group (order by sm.ncsf::double precision) as ncsf_q3,
        max(sm.ncsf) as ncsf_max,
        count(sm.ncsf) as ncsf_n,
        min(sm.ncsfl) as ncsfl_min,
        percentile_cont(0.25) within group (order by sm.ncsfl::double precision) as ncsfl_q1,
        percentile_cont(0.5) within group (order by sm.ncsfl::double precision) as ncsfl_median,
        percentile_cont(0.75) within group (order by sm.ncsfl::double precision) as ncsfl_q3,
        max(sm.ncsfl) as ncsfl_max,
        count(sm.ncsfl) as ncsfl_n,
        min(sm.nps) as nps_min,
        percentile_cont(0.25) within group (order by sm.nps::double precision) as nps_q1,
        percentile_cont(0.5) within group (order by sm.nps::double precision) as nps_median,
        percentile_cont(0.75) within group (order by sm.nps::double precision) as nps_q3,
        max(sm.nps) as nps_max,
        count(sm.nps) as nps_n,
        min(sm.cpsf) as cpsf_min,
        percentile_cont(0.25) within group (order by sm.cpsf::double precision) as cpsf_q1,
        percentile_cont(0.5) within group (order by sm.cpsf::double precision) as cpsf_median,
        percentile_cont(0.75) within group (order by sm.cpsf::double precision) as cpsf_q3,
        max(sm.cpsf) as cpsf_max,
        count(sm.cpsf) as cpsf_n,
        min(sm.npsfl) as npsfl_min,
        percentile_cont(0.25) within group (order by sm.npsfl::double precision) as npsfl_q1,
        percentile_cont(0.5) within group (order by sm.npsfl::double precision) as npsfl_median,
        percentile_cont(0.75) within group (order by sm.npsfl::double precision) as npsfl_q3,
        max(sm.npsfl) as npsfl_max,
        count(sm.npsfl) as npsfl_n,
        min(sm.npciting) as npciting_min,
        percentile_cont(0.25) within group (order by sm.npciting::double precision) as npciting_q1,
        percentile_cont(0.5) within group (order by sm.npciting::double precision) as npciting_median,
        percentile_cont(0.75) within group (order by sm.npciting::double precision) as npciting_q3,
        max(sm.npciting) as npciting_max,
        count(sm.npciting) as npciting_n,
        min(sm.rank_ns) as rank_ns_min,
        percentile_cont(0.25) within group (order by sm.rank_ns::double precision) as rank_ns_q1,
        percentile_cont(0.5) within group (order by sm.rank_ns::double precision) as rank_ns_median,
        percentile_cont(0.75) within group (order by sm.rank_ns::double precision) as rank_ns_q3,
        max(sm.rank_ns) as rank_ns_max,
        count(sm.rank_ns) as rank_ns_n,
        min(sm.c_ns) as c_ns_min,
        percentile_cont(0.25) within group (order by sm.c_ns::double precision) as c_ns_q1,
        percentile_cont(0.5) within group (order by sm.c_ns::double precision) as c_ns_median,
        percentile_cont(0.75) within group (order by sm.c_ns::double precision) as c_ns_q3,
        max(sm.c_ns) as c_ns_max,
        count(sm.c_ns) as c_ns_n,
        min(sm.nc_ns) as nc_ns_min,
        percentile_cont(0.25) within group (order by sm.nc_ns::double precision) as nc_ns_q1,
        percentile_cont(0.5) within group (order by sm.nc_ns::double precision) as nc_ns_median,
        percentile_cont(0.75) within group (order by sm.nc_ns::double precision) as nc_ns_q3,
        max(sm.nc_ns) as nc_ns_max,
        count(sm.nc_ns) as nc_ns_n,
        min(sm.h_ns) as h_ns_min,
        percentile_cont(0.25) within group (order by sm.h_ns::double precision) as h_ns_q1,
        percentile_cont(0.5) within group (order by sm.h_ns::double precision) as h_ns_median,
        percentile_cont(0.75) within group (order by sm.h_ns::double precision) as h_ns_q3,
        max(sm.h_ns) as h_ns_max,
        count(sm.h_ns) as h_ns_n,
        min(sm.hm_ns) as hm_ns_min,
        percentile_cont(0.25) within group (order by sm.hm_ns::double precision) as hm_ns_q1,
        percentile_cont(0.5) within group (order by sm.hm_ns::double precision) as hm_ns_median,
        percentile_cont(0.75) within group (order by sm.hm_ns::double precision) as hm_ns_q3,
        max(sm.hm_ns) as hm_ns_max,
        count(sm.hm_ns) as hm_ns_n,
        min(sm.ncs_ns) as ncs_ns_min,
        percentile_cont(0.25) within group (order by sm.ncs_ns::double precision) as ncs_ns_q1,
        percentile_cont(0.5) within group (order by sm.ncs_ns::double precision) as ncs_ns_median,
        percentile_cont(0.75) within group (order by sm.ncs_ns::double precision) as ncs_ns_q3,
        max(sm.ncs_ns) as ncs_ns_max,
        count(sm.ncs_ns) as ncs_ns_n,
        min(sm.ncsf_ns) as ncsf_ns_min,
        percentile_cont(0.25) within group (order by sm.ncsf_ns::double precision) as ncsf_ns_q1,
        percentile_cont(0.5) within group (order by sm.ncsf_ns::double precision) as ncsf_ns_median,
        percentile_cont(0.75) within group (order by sm.ncsf_ns::double precision) as ncsf_ns_q3,
        max(sm.ncsf_ns) as ncsf_ns_max,
        count(sm.ncsf_ns) as ncsf_ns_n,
        min(sm.ncsfl_ns) as ncsfl_ns_min,
        percentile_cont(0.25) within group (order by sm.ncsfl_ns::double precision) as ncsfl_ns_q1,
        percentile_cont(0.5) within group (order by sm.ncsfl_ns::double precision) as ncsfl_ns_median,
        percentile_cont(0.75) within group (order by sm.ncsfl_ns::double precision) as ncsfl_ns_q3,
        max(sm.ncsfl_ns) as ncsfl_ns_max,
        count(sm.ncsfl_ns) as ncsfl_ns_n,
        min(sm.nps_ns) as nps_ns_min,
        percentile_cont(0.25) within group (order by sm.nps_ns::double precision) as nps_ns_q1,
        percentile_cont(0.5) within group (order by sm.nps_ns::double precision) as nps_ns_median,
        percentile_cont(0.75) within group (order by sm.nps_ns::double precision) as nps_ns_q3,
        max(sm.nps_ns) as nps_ns_max,
        count(sm.nps_ns) as nps_ns_n,
        min(sm.cpsf_ns) as cpsf_ns_min,
        percentile_cont(0.25) within group (order by sm.cpsf_ns::double precision) as cpsf_ns_q1,
        percentile_cont(0.5) within group (order by sm.cpsf_ns::double precision) as cpsf_ns_median,
        percentile_cont(0.75) within group (order by sm.cpsf_ns::double precision) as cpsf_ns_q3,
        max(sm.cpsf_ns) as cpsf_ns_max,
        count(sm.cpsf_ns) as cpsf_ns_n,
        min(sm.npsfl_ns) as npsfl_ns_min,
        percentile_cont(0.25) within group (order by sm.npsfl_ns::double precision) as npsfl_ns_q1,
        percentile_cont(0.5) within group (order by sm.npsfl_ns::double precision) as npsfl_ns_median,
        percentile_cont(0.75) within group (order by sm.npsfl_ns::double precision) as npsfl_ns_q3,
        max(sm.npsfl_ns) as npsfl_ns_max,
        count(sm.npsfl_ns) as npsfl_ns_n,
        min(sm.npciting_ns) as npciting_ns_min,
        percentile_cont(0.25) within group (order by sm.npciting_ns::double precision) as npciting_ns_q1,
        percentile_cont(0.5) within group (order by sm.npciting_ns::double precision) as npciting_ns_median,
        percentile_cont(0.75) within group (order by sm.npciting_ns::double precision) as npciting_ns_q3,
        max(sm.npciting_ns) as npciting_ns_max,
        count(sm.npciting_ns) as npciting_ns_n,
        min(sm.np) as np_min,
        percentile_cont(0.25) within group (order by sm.np::double precision) as np_q1,
        percentile_cont(0.5) within group (order by sm.np::double precision) as np_median,
        percentile_cont(0.75) within group (order by sm.np::double precision) as np_q3,
        max(sm.np) as np_max,
        count(sm.np) as np_n,
        min(sm.self_pct) as self_pct_min,
        percentile_cont(0.25) within group (order by sm.self_pct::double precision) as self_pct_q1,
        percentile_cont(0.5) within group (order by sm.self_pct::double precision) as self_pct_median,
        percentile_cont(0.75) within group (order by sm.self_pct::double precision) as self_pct_q3,
        max(sm.self_pct) as self_pct_max,
        count(sm.self_pct) as self_pct_n
    from singleyr_metrics sm
    join fields f on f.field_id = sm.field_id
    where sm.field_id is not null
    group by sm.edition_id, f.name
)
select edition_id, 'cntry'::text as group_kind, group_value, metric,
       min, q1, median, q3, max, n
from career_wide_cntry
cross join lateral (values
            ('rank', rank_min::double precision, rank_q1, rank_median, rank_q3, rank_max::double precision, rank_n),
            ('c', c_min::double precision, c_q1, c_median, c_q3, c_max::double precision, c_n),
            ('nc', nc_min::double precision, nc_q1, nc_median, nc_q3, nc_max::double precision, nc_n),
            ('h', h_min::double precision, h_q1, h_median, h_q3, h_max::double precision, h_n),
            ('hm', hm_min::double precision, hm_q1, hm_median, hm_q3, hm_max::double precision, hm_n),
            ('ncs', ncs_min::double precision, ncs_q1, ncs_median, ncs_q3, ncs_max::double precision, ncs_n),
            ('ncsf', ncsf_min::double precision, ncsf_q1, ncsf_median, ncsf_q3, ncsf_max::double precision, ncsf_n),
            ('ncsfl', ncsfl_min::double precision, ncsfl_q1, ncsfl_median, ncsfl_q3, ncsfl_max::double precision, ncsfl_n),
            ('nps', nps_min::double precision, nps_q1, nps_median, nps_q3, nps_max::double precision, nps_n),
            ('cpsf', cpsf_min::double precision, cpsf_q1, cpsf_median, cpsf_q3, cpsf_max::double precision, cpsf_n),
            ('npsfl', npsfl_min::double precision, npsfl_q1, npsfl_median, npsfl_q3, npsfl_max::double precision, npsfl_n),
            ('npciting', npciting_min::double precision, npciting_q1, npciting_median, npciting_q3, npciting_max::double precision, npciting_n),
            ('rank_ns', rank_ns_min::double precision, rank_ns_q1, rank_ns_median, rank_ns_q3, rank_ns_max::double precision, rank_ns_n),
            ('c_ns', c_ns_min::double precision, c_ns_q1, c_ns_median, c_ns_q3, c_ns_max::double precision, c_ns_n),
            ('nc_ns', nc_ns_min::double precision, nc_ns_q1, nc_ns_median, nc_ns_q3, nc_ns_max::double precision, nc_ns_n),
            ('h_ns', h_ns_min::double precision, h_ns_q1, h_ns_median, h_ns_q3, h_ns_max::double precision, h_ns_n),
            ('hm_ns', hm_ns_min::double precision, hm_ns_q1, hm_ns_median, hm_ns_q3, hm_ns_max::double precision, hm_ns_n),
            ('ncs_ns', ncs_ns_min::double precision, ncs_ns_q1, ncs_ns_median, ncs_ns_q3, ncs_ns_max::double precision, ncs_ns_n),
            ('ncsf_ns', ncsf_ns_min::double precision, ncsf_ns_q1, ncsf_ns_median, ncsf_ns_q3, ncsf_ns_max::double precision, ncsf_ns_n),
            ('ncsfl_ns', ncsfl_ns_min::double precision, ncsfl_ns_q1, ncsfl_ns_median, ncsfl_ns_q3, ncsfl_ns_max::double precision, ncsfl_ns_n),
            ('nps_ns', nps_ns_min::double precision, nps_ns_q1, nps_ns_median, nps_ns_q3, nps_ns_max::double precision, nps_ns_n),
            ('cpsf_ns', cpsf_ns_min::double precision, cpsf_ns_q1, cpsf_ns_median, cpsf_ns_q3, cpsf_ns_max::double precision, cpsf_ns_n),
            ('npsfl_ns', npsfl_ns_min::double precision, npsfl_ns_q1, npsfl_ns_median, npsfl_ns_q3, npsfl_ns_max::double precision, npsfl_ns_n),
            ('npciting_ns', npciting_ns_min::double precision, npciting_ns_q1, npciting_ns_median, npciting_ns_q3, npciting_ns_max::double precision, npciting_ns_n),
            ('np', np_min::double precision, np_q1, np_median, np_q3, np_max::double precision, np_n),
            ('self_pct', self_pct_min::double precision, self_pct_q1, self_pct_median, self_pct_q3, self_pct_max::double precision, self_pct_n)
) as v(metric, min, q1, median, q3, max, n)
union all
select edition_id, 'sm-field'::text as group_kind, group_value, metric,
       min, q1, median, q3, max, n
from career_wide_field
cross join lateral (values
            ('rank', rank_min::double precision, rank_q1, rank_median, rank_q3, rank_max::double precision, rank_n),
            ('c', c_min::double precision, c_q1, c_median, c_q3, c_max::double precision, c_n),
            ('nc', nc_min::double precision, nc_q1, nc_median, nc_q3, nc_max::double precision, nc_n),
            ('h', h_min::double precision, h_q1, h_median, h_q3, h_max::double precision, h_n),
            ('hm', hm_min::double precision, hm_q1, hm_median, hm_q3, hm_max::double precision, hm_n),
            ('ncs', ncs_min::double precision, ncs_q1, ncs_median, ncs_q3, ncs_max::double precision, ncs_n),
            ('ncsf', ncsf_min::double precision, ncsf_q1, ncsf_median, ncsf_q3, ncsf_max::double precision, ncsf_n),
            ('ncsfl', ncsfl_min::double precision, ncsfl_q1, ncsfl_median, ncsfl_q3, ncsfl_max::double precision, ncsfl_n),
            ('nps', nps_min::double precision, nps_q1, nps_median, nps_q3, nps_max::double precision, nps_n),
            ('cpsf', cpsf_min::double precision, cpsf_q1, cpsf_median, cpsf_q3, cpsf_max::double precision, cpsf_n),
            ('npsfl', npsfl_min::double precision, npsfl_q1, npsfl_median, npsfl_q3, npsfl_max::double precision, npsfl_n),
            ('npciting', npciting_min::double precision, npciting_q1, npciting_median, npciting_q3, npciting_max::double precision, npciting_n),
            ('rank_ns', rank_ns_min::double precision, rank_ns_q1, rank_ns_median, rank_ns_q3, rank_ns_max::double precision, rank_ns_n),
            ('c_ns', c_ns_min::double precision, c_ns_q1, c_ns_median, c_ns_q3, c_ns_max::double precision, c_ns_n),
            ('nc_ns', nc_ns_min::double precision, nc_ns_q1, nc_ns_median, nc_ns_q3, nc_ns_max::double precision, nc_ns_n),
            ('h_ns', h_ns_min::double precision, h_ns_q1, h_ns_median, h_ns_q3, h_ns_max::double precision, h_ns_n),
            ('hm_ns', hm_ns_min::double precision, hm_ns_q1, hm_ns_median, hm_ns_q3, hm_ns_max::double precision, hm_ns_n),
            ('ncs_ns', ncs_ns_min::double precision, ncs_ns_q1, ncs_ns_median, ncs_ns_q3, ncs_ns_max::double precision, ncs_ns_n),
            ('ncsf_ns', ncsf_ns_min::double precision, ncsf_ns_q1, ncsf_ns_median, ncsf_ns_q3, ncsf_ns_max::double precision, ncsf_ns_n),
            ('ncsfl_ns', ncsfl_ns_min::double precision, ncsfl_ns_q1, ncsfl_ns_median, ncsfl_ns_q3, ncsfl_ns_max::double precision, ncsfl_ns_n),
            ('nps_ns', nps_ns_min::double precision, nps_ns_q1, nps_ns_median, nps_ns_q3, nps_ns_max::double precision, nps_ns_n),
            ('cpsf_ns', cpsf_ns_min::double precision, cpsf_ns_q1, cpsf_ns_median, cpsf_ns_q3, cpsf_ns_max::double precision, cpsf_ns_n),
            ('npsfl_ns', npsfl_ns_min::double precision, npsfl_ns_q1, npsfl_ns_median, npsfl_ns_q3, npsfl_ns_max::double precision, npsfl_ns_n),
            ('npciting_ns', npciting_ns_min::double precision, npciting_ns_q1, npciting_ns_median, npciting_ns_q3, npciting_ns_max::double precision, npciting_ns_n),
            ('np', np_min::double precision, np_q1, np_median, np_q3, np_max::double precision, np_n),
            ('self_pct', self_pct_min::double precision, self_pct_q1, self_pct_median, self_pct_q3, self_pct_max::double precision, self_pct_n)
) as v(metric, min, q1, median, q3, max, n)
union all
select edition_id, 'cntry'::text as group_kind, group_value, metric,
       min, q1, median, q3, max, n
from singleyr_wide_cntry
cross join lateral (values
            ('rank', rank_min::double precision, rank_q1, rank_median, rank_q3, rank_max::double precision, rank_n),
            ('c', c_min::double precision, c_q1, c_median, c_q3, c_max::double precision, c_n),
            ('nc', nc_min::double precision, nc_q1, nc_median, nc_q3, nc_max::double precision, nc_n),
            ('h', h_min::double precision, h_q1, h_median, h_q3, h_max::double precision, h_n),
            ('hm', hm_min::double precision, hm_q1, hm_median, hm_q3, hm_max::double precision, hm_n),
            ('ncs', ncs_min::double precision, ncs_q1, ncs_median, ncs_q3, ncs_max::double precision, ncs_n),
            ('ncsf', ncsf_min::double precision, ncsf_q1, ncsf_median, ncsf_q3, ncsf_max::double precision, ncsf_n),
            ('ncsfl', ncsfl_min::double precision, ncsfl_q1, ncsfl_median, ncsfl_q3, ncsfl_max::double precision, ncsfl_n),
            ('nps', nps_min::double precision, nps_q1, nps_median, nps_q3, nps_max::double precision, nps_n),
            ('cpsf', cpsf_min::double precision, cpsf_q1, cpsf_median, cpsf_q3, cpsf_max::double precision, cpsf_n),
            ('npsfl', npsfl_min::double precision, npsfl_q1, npsfl_median, npsfl_q3, npsfl_max::double precision, npsfl_n),
            ('npciting', npciting_min::double precision, npciting_q1, npciting_median, npciting_q3, npciting_max::double precision, npciting_n),
            ('rank_ns', rank_ns_min::double precision, rank_ns_q1, rank_ns_median, rank_ns_q3, rank_ns_max::double precision, rank_ns_n),
            ('c_ns', c_ns_min::double precision, c_ns_q1, c_ns_median, c_ns_q3, c_ns_max::double precision, c_ns_n),
            ('nc_ns', nc_ns_min::double precision, nc_ns_q1, nc_ns_median, nc_ns_q3, nc_ns_max::double precision, nc_ns_n),
            ('h_ns', h_ns_min::double precision, h_ns_q1, h_ns_median, h_ns_q3, h_ns_max::double precision, h_ns_n),
            ('hm_ns', hm_ns_min::double precision, hm_ns_q1, hm_ns_median, hm_ns_q3, hm_ns_max::double precision, hm_ns_n),
            ('ncs_ns', ncs_ns_min::double precision, ncs_ns_q1, ncs_ns_median, ncs_ns_q3, ncs_ns_max::double precision, ncs_ns_n),
            ('ncsf_ns', ncsf_ns_min::double precision, ncsf_ns_q1, ncsf_ns_median, ncsf_ns_q3, ncsf_ns_max::double precision, ncsf_ns_n),
            ('ncsfl_ns', ncsfl_ns_min::double precision, ncsfl_ns_q1, ncsfl_ns_median, ncsfl_ns_q3, ncsfl_ns_max::double precision, ncsfl_ns_n),
            ('nps_ns', nps_ns_min::double precision, nps_ns_q1, nps_ns_median, nps_ns_q3, nps_ns_max::double precision, nps_ns_n),
            ('cpsf_ns', cpsf_ns_min::double precision, cpsf_ns_q1, cpsf_ns_median, cpsf_ns_q3, cpsf_ns_max::double precision, cpsf_ns_n),
            ('npsfl_ns', npsfl_ns_min::double precision, npsfl_ns_q1, npsfl_ns_median, npsfl_ns_q3, npsfl_ns_max::double precision, npsfl_ns_n),
            ('npciting_ns', npciting_ns_min::double precision, npciting_ns_q1, npciting_ns_median, npciting_ns_q3, npciting_ns_max::double precision, npciting_ns_n),
            ('np', np_min::double precision, np_q1, np_median, np_q3, np_max::double precision, np_n),
            ('self_pct', self_pct_min::double precision, self_pct_q1, self_pct_median, self_pct_q3, self_pct_max::double precision, self_pct_n)
) as v(metric, min, q1, median, q3, max, n)
union all
select edition_id, 'sm-field'::text as group_kind, group_value, metric,
       min, q1, median, q3, max, n
from singleyr_wide_field
cross join lateral (values
            ('rank', rank_min::double precision, rank_q1, rank_median, rank_q3, rank_max::double precision, rank_n),
            ('c', c_min::double precision, c_q1, c_median, c_q3, c_max::double precision, c_n),
            ('nc', nc_min::double precision, nc_q1, nc_median, nc_q3, nc_max::double precision, nc_n),
            ('h', h_min::double precision, h_q1, h_median, h_q3, h_max::double precision, h_n),
            ('hm', hm_min::double precision, hm_q1, hm_median, hm_q3, hm_max::double precision, hm_n),
            ('ncs', ncs_min::double precision, ncs_q1, ncs_median, ncs_q3, ncs_max::double precision, ncs_n),
            ('ncsf', ncsf_min::double precision, ncsf_q1, ncsf_median, ncsf_q3, ncsf_max::double precision, ncsf_n),
            ('ncsfl', ncsfl_min::double precision, ncsfl_q1, ncsfl_median, ncsfl_q3, ncsfl_max::double precision, ncsfl_n),
            ('nps', nps_min::double precision, nps_q1, nps_median, nps_q3, nps_max::double precision, nps_n),
            ('cpsf', cpsf_min::double precision, cpsf_q1, cpsf_median, cpsf_q3, cpsf_max::double precision, cpsf_n),
            ('npsfl', npsfl_min::double precision, npsfl_q1, npsfl_median, npsfl_q3, npsfl_max::double precision, npsfl_n),
            ('npciting', npciting_min::double precision, npciting_q1, npciting_median, npciting_q3, npciting_max::double precision, npciting_n),
            ('rank_ns', rank_ns_min::double precision, rank_ns_q1, rank_ns_median, rank_ns_q3, rank_ns_max::double precision, rank_ns_n),
            ('c_ns', c_ns_min::double precision, c_ns_q1, c_ns_median, c_ns_q3, c_ns_max::double precision, c_ns_n),
            ('nc_ns', nc_ns_min::double precision, nc_ns_q1, nc_ns_median, nc_ns_q3, nc_ns_max::double precision, nc_ns_n),
            ('h_ns', h_ns_min::double precision, h_ns_q1, h_ns_median, h_ns_q3, h_ns_max::double precision, h_ns_n),
            ('hm_ns', hm_ns_min::double precision, hm_ns_q1, hm_ns_median, hm_ns_q3, hm_ns_max::double precision, hm_ns_n),
            ('ncs_ns', ncs_ns_min::double precision, ncs_ns_q1, ncs_ns_median, ncs_ns_q3, ncs_ns_max::double precision, ncs_ns_n),
            ('ncsf_ns', ncsf_ns_min::double precision, ncsf_ns_q1, ncsf_ns_median, ncsf_ns_q3, ncsf_ns_max::double precision, ncsf_ns_n),
            ('ncsfl_ns', ncsfl_ns_min::double precision, ncsfl_ns_q1, ncsfl_ns_median, ncsfl_ns_q3, ncsfl_ns_max::double precision, ncsfl_ns_n),
            ('nps_ns', nps_ns_min::double precision, nps_ns_q1, nps_ns_median, nps_ns_q3, nps_ns_max::double precision, nps_ns_n),
            ('cpsf_ns', cpsf_ns_min::double precision, cpsf_ns_q1, cpsf_ns_median, cpsf_ns_q3, cpsf_ns_max::double precision, cpsf_ns_n),
            ('npsfl_ns', npsfl_ns_min::double precision, npsfl_ns_q1, npsfl_ns_median, npsfl_ns_q3, npsfl_ns_max::double precision, npsfl_ns_n),
            ('npciting_ns', npciting_ns_min::double precision, npciting_ns_q1, npciting_ns_median, npciting_ns_q3, npciting_ns_max::double precision, npciting_ns_n),
            ('np', np_min::double precision, np_q1, np_median, np_q3, np_max::double precision, np_n),
            ('self_pct', self_pct_min::double precision, self_pct_q1, self_pct_median, self_pct_q3, self_pct_max::double precision, self_pct_n)
) as v(metric, min, q1, median, q3, max, n)
with data;

create unique index group_metrics_key_idx
    on group_metrics (edition_id, group_kind, group_value, metric);
